### ISSUE TITLE
Rewrite section on DynamicFeatureFilter without time indicator

### ISSUE THREAD

**Issue by ttho** [aixm/WFS-TE#14]
no time indicator = [start of universe] to [end of universe]

**Comment by ttho** [comment]
Section rewritten, to be reviewed. Slight change of definition:

no time indicator = all time periods of active BASELINEs

Otherwise the result will always be empty, because of the definition of isDefined(t, f): "... for the whole time period t..."

**Comment by vog** [comment]
Idea, related to this: New flag "strict" flag, which is completely independent of matchAny / matchAll.

**Comment by ttho** [comment]
The default value should be false. The strict flag applies to queries with time indicator as well.
Cases:
- no time indicator, strict = false: all possible snapshots are generated and evaluated by a standard WFS filter
- no time indicator, strict = true: all possible snapshots are generated. If the set of snapshots is not temporally contiguous, an error is returned. Otherwise it is evaluated by a standard WFS filter. 
- with time indicator, strict = false: the minimum set of snapshots covering the time indicator is generated and evaluated by a standard WFS filter
- with time indicator, strict = true: the minimum set of snapshots covering the time indicator is generated. If the set is not contiguous, or time range covered by the set does not (fully) contain the time indicator, an error is returned. Otherwise it is evaluated by a standard WFS filter.

**Comment by ttho** [comment]
Sections updated. Also changed the definition for the minimum set of SNAPSHOT time slices, which is then reused for DynamicFeatureFilter and SnapshotGeneration. Ready for review.
