### ISSUE TITLE
Application of transformations and projections when resolving associations

### ISSUE THREAD

**Issue by ttho** [aixm/WFS-TE#16]
Default is resolve="none" which means not to resolve any (XLink) references.
- If resolve="local", XLink references to other features are to be replaced by the object where it points to if the referenced object is located on the same server.
- If resolve="remote", XLink references to other features are to be replaced by the object where it points to if the referenced object is located on a different server.
- resolve="all" includes "local" and "remote"

There are two issues:
1. AIXM defines abstract references which are not covered by the XLink standard. Should resolution resolve abstract references, too?
2. In AIXM feature associations link time slices to whole features. This means the XLink will be replaced by the whole feature pointed to including its full history of time slices. If SnapshotGeneration is requested by the client, this may be
   - too verbose and inefficient and 
   - requires the client to apply the AIXM Temporality Model to the resolved feature, which is something we generally want the client to relieve from with WFS-TE.

Proposal: 
- add requirement that resolution is to be applied to abstract references as well
- add requirement to SnapshotGeneration, that resolved features only contain the SNAPSHOT time slice(s) of the requested point in time / time range (or the dummy time slice if not available). Please note that for multiple SNAPSHOT time slices in the response this requires the referenced feature to appear in each time slice even if unchanged because of the changing SNAPSHOT time / time range.
- add conformance classe(s) for support of (each?) of the above requirements 
- update section on querying backward references, as the resolve operation adds a second option 

Alternative: explicitly exclude the resolution of abstract references

**Comment by ttho** [comment]
From Sep 24th's Telco:
- There is no replacement of content, instead resolved references are placed in the 'AdditionalObjects' section of the WFS response and the XLinks are replaced by local XLinks (#).
- Volker pointed out that abstract references may be covered by the XLink standard. Someone should check this.
- we decided that for simplification, all present projection and transformation clauses are to be applied to the resolved features as well

**Comment by ttho** [comment]
Action (Volker): add requirement to core, add additional option to query for associated features

**Comment by vog** [comment]
Added requirements class "/req/core/project-and-transform-additional-objects".

@ttho Please check if it contains all necessary information from the ticket.
