### ISSUE TITLE
Update link to "Use of Geography Markup Language (GML) for Aviation Data"

### ISSUE THREAD

**Issue by vog** [aixm/WFS-TE#22]
I believe that at some place, the documents links (or should link) to:

"Use of Geography Markup Language (GML) for Aviation Data"

However, I can't find the exact place in the document. Wherever it is, we now have a public link for that:
- https://portal.opengeospatial.org/files/?artifact_id=62061

(The old link required an OGC portal login, and didn't point to the very latest edition of the document.)

**Comment by ttho** [comment]
Added to references and referenced where AIXM Feature Identification and Reference was linked.
