### ISSUE TITLE
Clarify multiple DynamicFeatureQuery

### ISSUE THREAD

**Issue by vog** [aixm/WFS-TE#25]
Clarify how a WFS request with multiple DynamicFeatureQuery elements should be executed. Open questions (list may be incomplete):
- If the same feature is returned by multiple DynamicFeatureQuery results, these have to be merged, otherwise their `gml:id`s would clash. However, if these have different projection/transformation clauses, which version should appear in the result?
- If resolveDepth is set, the additional features could come from different DynamicFeatureQuery results which reference them. What projection/transformation should these have? (see #16)

This leads to the following questions:
- Should we disallow more than one DynamicFeatureQuery per WFS request. (However, "normal" WFS requests are allowed to have more than one Query)
- Should we enforce that all DynamicFeatureQuery always have the exact same projections and transformations?

**Comment by vog** [comment]
Current solution in deegree:
- All results are concatenated together
- Duplicate features are local XLink references to previous features
- So effectively, for each feature the first variant (projection/transformation) is returned

**Comment by ttho** [comment]
I suggest creating new gml:ids for clashing features, perhaps by appending a counter? That breaks standard, I know, but nothing that isn't already broken ;). Projections are defined in WFS already, and multiple queries can be executed with different projections, finally resulting in exact the issue you describe.

**Comment by vog** [comment]
> I suggest creating new gml:ids for clashing features, perhaps by appending a counter?

The problem is that in a WFS it is expected to be possible to find a feature by its gml:id. Moreover, in AIXM the feature gml:id's are expected to be of the form "uuid.<UUID>".

> Projections are defined in WFS already, and multiple queries can be executed with different projections, finally resulting in exact the issue you describe.

Good point. So it may be sufficient to say that every WFS is expected to solve this issue in some way. And that for temporality exactly the same solution is to be applied (whatever it is).

For example, the above solution in deegree is essentially what deegree also does in normal (non-temporal) operation.
