### ISSUE TITLE
Rules for basic AIXM 5.1 temporality sanity

### ISSUE THREAD

**Issue by vog** [aixm/WFS-TE#3]
Create rules for basic AIXM 5.1 temporality sanity.
- Volker will propose informal descriptions of rules
- Eddy will create SBVR from information description
- Eddy will create Schematron from SBVR

Some rules:
- featureLifeime must not change throughout the (corrected) BASELINEs, except for the last one (which may be a decommissioning)

**Comment by ttho** [comment]
- featureLifetime start is consistent for all (active) BASELINEs
- featureLifetime.start equals validTime.beginPosition for the first BASELINE
- featureLifetime end is only set in the last BASELINE, and equals the validTime.endPosition

**Comment by ttho** [comment]
- no doubled correction is allowed
- no doubled commissioning, decommissioning
- check correction number (does precedessor exist?)

**Comment by ttho** [comment]
To be defined in AIXM Temporality Model V1.1, link to there once ready. Check the draft if there is enough information for us.

**Comment by vog** [comment]
Replacing this with #24.
